let mySprite = sprites.create(assets.image`Naruto`, SpriteKind.Player)
controller.moveSprite(mySprite)
scene.setBackgroundColor(9)
let mySprite2 = sprites.create(assets.image`Tanjiro`, SpriteKind.Player)
let mySprite3 = sprites.create(assets.image`Pain`, SpriteKind.Projectile)
mySprite2.setPosition(128, 84)
